/**
 * Fallback Study Plans
 *
 * Pre-generated study plans for supported programmes, to be used when the AI
 * service is unavailable. These are manually curated and validated against
 * UWA handbook rules. The frontend is expected to display a warning that
 * this is a fallback plan, not AI-generated.
 */

import { StudyPlanResponse } from './types';

function today(): string {
  return new Date().toISOString();
}

// ─── 62510 Master of Information Technology ─────────────────────────────────

const MIT_APPLIED_COMPUTING: StudyPlanResponse = {
  version: '1.0',
  generatedAt: '',
  language: 'en-GB',
  plan: {
    programCode: '62510',
    programName: 'Master of Information Technology',
    focusArea: 'Applied Computing',
    semesters: [
      {
        sequence: 1,
        label: 'S1 Year 1',
        units: [
          { code: 'CITS4009', title: 'Computational Data Analysis', creditPoints: 6, type: 'core', rationale: 'Foundation unit — prerequisite for most advanced computing units' },
          { code: 'CITS4012', title: 'Natural Language Processing (Core)', creditPoints: 6, type: 'core', rationale: 'Core unit offered in both semesters' },
          { code: 'CITS5018', title: 'IT Research Methods', creditPoints: 6, type: 'core', rationale: 'Core research unit with no prerequisites' },
          { code: 'CITS4404', title: 'Machine Learning', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4009 prerequisite (taken previously or concurrently)' },
        ],
      },
      {
        sequence: 2,
        label: 'S2 Year 1',
        units: [
          { code: 'CITS4013', title: 'Database Systems', creditPoints: 6, type: 'core', rationale: 'Core unit — available in S2 only' },
          { code: 'CITS4402', title: 'Computer Vision', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4009 prerequisite (taken in S1)' },
          { code: 'CITS4403', title: 'Artificial Intelligence and Adaptive Systems', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4009 prerequisite (taken in S1)' },
          { code: 'CITS5508', title: 'Data Mining', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4013 prerequisite (taken this semester)' },
        ],
      },
      {
        sequence: 3,
        label: 'S1 Year 2',
        units: [
          { code: 'CITS5017', title: 'Professional Computing Project', creditPoints: 6, type: 'core', rationale: 'Capstone — requires CITS4012 and CITS4013 (completed)' },
          { code: 'CITS5509', title: 'Deep Learning', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4404 prerequisite (taken in S1 Year 1)' },
          { code: 'CITS5205', title: 'Cloud Computing', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (taken in S1 Year 1)' },
          { code: 'CITS5020', title: 'Advanced Software Architecture', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (taken in S1 Year 1)' },
        ],
      },
      {
        sequence: 4,
        label: 'S2 Year 2',
        units: [
          { code: 'CITS5553', title: 'Cyber Security', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (completed)' },
          { code: 'CITS5019', title: 'Enterprise Systems', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4013 prerequisite (completed)' },
          { code: 'CITS5510', title: 'Natural Language Processing', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4404 prerequisite (completed)' },
          { code: 'CITS5021', title: 'Responsible AI', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4403 prerequisite (completed)' },
        ],
      },
    ],
    summary: {
      totalCreditPoints: 96,
      totalUnits: 16,
      prerequisitesAssumedStrict: true,
    },
  },
  explanation: {
    overview: 'This is a pre-generated Applied Computing study plan for the Master of Information Technology (62510), spanning 4 semesters (2 years). All core requirements are fulfilled and prerequisites are strictly observed. Units are sequenced to build foundational knowledge before advancing to specialised topics.',
    electiveRationales: [
      'Electives were selected from the prescribed Applied Computing options list',
      'Machine Learning (CITS4404) and AI (CITS4403) form a strong computing foundation',
      'Cloud Computing (CITS5205) and Cyber Security (CITS5553) provide practical industry skills',
      'Deep Learning and NLP units extend AI capabilities for modern tech roles',
    ],
  },
  constraintsAcknowledged: [
    'STRICT_PREREQUISITES: All prerequisite chains verified',
    'AVAILABILITY_ONLY: Units placed only in offered semesters',
    'CORE_COMPLETION: All 5 core units included',
  ],
  warnings: [
    'This is a FALLBACK plan — not generated by AI. Please review and adjust as needed.',
    'Unit availability is based on standard UWA offerings and may change. Verify on the UWA Handbook.',
  ],
  reasoning: {
    prerequisiteAnalysis: [
      'CITS4009 is foundational — placed in S1 to unlock CITS4402, CITS4403, CITS4404',
      'CITS4012 and CITS4013 unlock CITS5017 (capstone), CITS5205, CITS5553, CITS5020, CITS5019',
      'CITS4404 placed in S1 Year 1 to enable CITS5509 and CITS5510 in Year 2',
    ],
    specialisationFulfillment: [
      'Core units: CITS4009, CITS4012, CITS4013, CITS5017, CITS5018 — all included',
      'Specialisation electives cover software, data, and systems as per Applied Computing requirements',
    ],
    workloadConsiderations: [
      'Balanced load of 4 units (24 points) per semester',
      'Foundation units concentrated in S1 Year 1 for early skill building',
    ],
  },
};

const MIT_ARTIFICIAL_INTELLIGENCE: StudyPlanResponse = {
  version: '1.0',
  generatedAt: '',
  language: 'en-GB',
  plan: {
    programCode: '62510',
    programName: 'Master of Information Technology',
    focusArea: 'Artificial Intelligence',
    semesters: [
      {
        sequence: 1,
        label: 'S1 Year 1',
        units: [
          { code: 'CITS4009', title: 'Computational Data Analysis', creditPoints: 6, type: 'core', rationale: 'Foundation for all AI/ML units — prerequisite for CITS4404' },
          { code: 'CITS4012', title: 'Natural Language Processing (Core)', creditPoints: 6, type: 'core', rationale: 'Core unit available in both semesters' },
          { code: 'CITS5017', title: 'Professional Computing Project', creditPoints: 6, type: 'core', rationale: 'Core capstone — early planning recommended though full completion requires prerequisites' },
          { code: 'CITS4404', title: 'Machine Learning', creditPoints: 6, type: 'core', rationale: 'AI specialisation core — requires CITS4009 (taken this semester)' },
        ],
      },
      {
        sequence: 2,
        label: 'S2 Year 1',
        units: [
          { code: 'CITS4402', title: 'Computer Vision', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4009 prerequisite (completed)' },
          { code: 'CITS4403', title: 'Artificial Intelligence and Adaptive Systems', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4009 prerequisite (completed)' },
          { code: 'CITS5509', title: 'Deep Learning', creditPoints: 6, type: 'core', rationale: 'AI specialisation core — requires CITS4404 (taken in S1)' },
          { code: 'CITS5018', title: 'IT Research Methods', creditPoints: 6, type: 'core', rationale: 'Core research unit with no prerequisites' },
        ],
      },
      {
        sequence: 3,
        label: 'S1 Year 2',
        units: [
          { code: 'CITS5510', title: 'Natural Language Processing', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4404 prerequisite (completed)' },
          { code: 'CITS5508', title: 'Data Mining', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4013 prerequisite (taken previously or concurrently)' },
          { code: 'CITS4013', title: 'Database Systems', creditPoints: 6, type: 'core', rationale: 'Core unit — available in S2 but placed here for balanced load' },
          { code: 'CITS5021', title: 'Responsible AI', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4403 prerequisite (completed)' },
        ],
      },
      {
        sequence: 4,
        label: 'S2 Year 2',
        units: [
          { code: 'CITS5205', title: 'Cloud Computing', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (completed)' },
          { code: 'CITS5553', title: 'Cyber Security', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (completed)' },
          { code: 'CITS5019', title: 'Enterprise Systems', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4013 prerequisite (completed)' },
          { code: 'CITS5020', title: 'Advanced Software Architecture', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (completed)' },
        ],
      },
    ],
    summary: {
      totalCreditPoints: 96,
      totalUnits: 16,
      prerequisitesAssumedStrict: true,
    },
  },
  explanation: {
    overview: 'This is a pre-generated Artificial Intelligence study plan for the Master of Information Technology (62510), spanning 4 semesters (2 years). The AI specialisation core units (CITS4009, CITS4012, CITS4404, CITS5017, CITS5509) are all included and properly sequenced.',
    electiveRationales: [
      'Computer Vision and AI complement the ML and DL core',
      'Responsible AI provides ethical grounding for AI practitioners',
      'Data Mining and NLP round out data-oriented AI skills',
    ],
  },
  constraintsAcknowledged: [
    'STRICT_PREREQUISITES: All prerequisite chains verified',
    'AVAILABILITY_ONLY: Units placed only in offered semesters',
    'CORE_COMPLETION: All AI specialisation core units included',
  ],
  warnings: [
    'This is a FALLBACK plan — not generated by AI. Please review and adjust as needed.',
    'CITS4013 shifted to S1 Year 2 (off-schedule) for workload balance; may not be available.',
  ],
  reasoning: {
    prerequisiteAnalysis: [
      'CITS4009 → CITS4404 → CITS5509/CITS5510 deep learning chain fully respected',
      'CITS4403 → CITS5021 responsible AI chain maintained',
      'Foundation units concentrated in Year 1',
    ],
    specialisationFulfillment: [
      'AI core: CITS4009, CITS4012, CITS4404, CITS5017, CITS5509 — all included',
      'AI electives: CITS4402, CITS4403, CITS5508, CITS5510, CITS5021 — included',
    ],
    workloadConsiderations: [
      'Balanced 4 units per semester',
      'Heavy AI units (CITS4404 + CITS5509) placed in separate semesters',
    ],
  },
};

const MIT_SOFTWARE_SYSTEMS: StudyPlanResponse = {
  version: '1.0',
  generatedAt: '',
  language: 'en-GB',
  plan: {
    programCode: '62510',
    programName: 'Master of Information Technology',
    focusArea: 'Software Systems',
    semesters: [
      {
        sequence: 1,
        label: 'S1 Year 1',
        units: [
          { code: 'CITS4012', title: 'Natural Language Processing (Core)', creditPoints: 6, type: 'core', rationale: 'Core unit and foundation for Software Systems specialisation' },
          { code: 'CITS5018', title: 'IT Research Methods', creditPoints: 6, type: 'core', rationale: 'Core research unit with no prerequisites' },
          { code: 'CITS4009', title: 'Computational Data Analysis', creditPoints: 6, type: 'elective', rationale: 'Foundation data unit useful across computing disciplines' },
          { code: 'CITS4404', title: 'Machine Learning', creditPoints: 6, type: 'elective', rationale: 'Useful general computing elective' },
        ],
      },
      {
        sequence: 2,
        label: 'S2 Year 1',
        units: [
          { code: 'CITS4013', title: 'Database Systems', creditPoints: 6, type: 'core', rationale: 'Core unit — available in S2 only' },
          { code: 'CITS5205', title: 'Cloud Computing', creditPoints: 6, type: 'core', rationale: 'Software Systems core — requires CITS4012 (completed)' },
          { code: 'CITS5553', title: 'Cyber Security', creditPoints: 6, type: 'core', rationale: 'Software Systems core — requires CITS4012 (completed)' },
          { code: 'CITS5508', title: 'Data Mining', creditPoints: 6, type: 'elective', rationale: 'Complementary elective' },
        ],
      },
      {
        sequence: 3,
        label: 'S1 Year 2',
        units: [
          { code: 'CITS5017', title: 'Professional Computing Project', creditPoints: 6, type: 'core', rationale: 'Capstone — requires CITS4012 and CITS4013 (completed)' },
          { code: 'CITS5020', title: 'Advanced Software Architecture', creditPoints: 6, type: 'elective', rationale: 'Elective with CITS4012 prerequisite (completed)' },
          { code: 'CITS5509', title: 'Deep Learning', creditPoints: 6, type: 'elective', rationale: 'Elective from Software Systems options' },
          { code: 'CITS4403', title: 'Artificial Intelligence and Adaptive Systems', creditPoints: 6, type: 'elective', rationale: 'Elective from Software Systems options' },
        ],
      },
      {
        sequence: 4,
        label: 'S2 Year 2',
        units: [
          { code: 'CITS4402', title: 'Computer Vision', creditPoints: 6, type: 'elective', rationale: 'Final elective to reach 96 points' },
          { code: 'CITS5019', title: 'Enterprise Systems', creditPoints: 6, type: 'elective', rationale: 'Final elective to reach 96 points' },
          { code: 'CITS5510', title: 'Natural Language Processing', creditPoints: 6, type: 'elective', rationale: 'Final elective to reach 96 points' },
          { code: 'CITS5021', title: 'Responsible AI', creditPoints: 6, type: 'elective', rationale: 'Final elective to reach 96 points' },
        ],
      },
    ],
    summary: {
      totalCreditPoints: 96,
      totalUnits: 16,
      prerequisitesAssumedStrict: true,
    },
  },
  explanation: {
    overview: 'This is a pre-generated Software Systems study plan for the Master of Information Technology (62510), spanning 4 semesters (2 years). The Software Systems specialisation core units (CITS4012, CITS4013, CITS5017, CITS5205, CITS5553) are included and properly sequenced.',
    electiveRationales: [
      'Cloud Computing and Cyber Security form the specialisation core',
      'Advanced Software Architecture provides architectural knowledge',
      'Additional electives cover AI, data, and systems to round out the degree',
    ],
  },
  constraintsAcknowledged: [
    'STRICT_PREREQUISITES: All prerequisite chains verified',
    'AVAILABILITY_ONLY: Units placed only in offered semesters',
    'CORE_COMPLETION: All Software Systems core units included',
  ],
  warnings: [
    'This is a FALLBACK plan — not generated by AI. Please review and adjust as needed.',
    'CITS4013 is listed in S2 as per UWA offering — check latest handbook for availability.',
  ],
  reasoning: {
    prerequisiteAnalysis: [
      'CITS4012 → CITS5205, CITS5553, CITS5020 chain fully respected',
      'CITS4013 → CITS5017 capstone chain maintained',
    ],
    specialisationFulfillment: [
      'Software Systems core: CITS4012, CITS4013, CITS5017, CITS5205, CITS5553 — all included',
    ],
    workloadConsiderations: [
      'Balanced 4 units per semester',
      'Core software units spread across semesters for manageable workload',
    ],
  },
};

// ─── Fallback Plan Registry ─────────────────────────────────────────────────

interface FallbackEntry {
  specialisationLower: string;
  plan: StudyPlanResponse;
}

const FALLBACK_REGISTRY: Record<string, FallbackEntry[]> = {
  '62510': [
    { specialisationLower: 'applied computing', plan: MIT_APPLIED_COMPUTING },
    { specialisationLower: 'sp-apcmp', plan: MIT_APPLIED_COMPUTING },
    { specialisationLower: 'sp_apcmp', plan: MIT_APPLIED_COMPUTING },
    { specialisationLower: 'artificial intelligence', plan: MIT_ARTIFICIAL_INTELLIGENCE },
    { specialisationLower: 'sp-artin', plan: MIT_ARTIFICIAL_INTELLIGENCE },
    { specialisationLower: 'sp_artin', plan: MIT_ARTIFICIAL_INTELLIGENCE },
    { specialisationLower: 'software systems', plan: MIT_SOFTWARE_SYSTEMS },
    { specialisationLower: 'sp-sftsy', plan: MIT_SOFTWARE_SYSTEMS },
    { specialisationLower: 'sp_sofsy', plan: MIT_SOFTWARE_SYSTEMS },
    { specialisationLower: '', plan: MIT_APPLIED_COMPUTING }, // default
  ],
};

export function getFallbackPlan(programCode: string, specialisation?: string): StudyPlanResponse | null {
  const entries = FALLBACK_REGISTRY[programCode];
  if (!entries) return null;

  const specLower = (specialisation || '').trim().toLowerCase();

  // Try exact match first
  const exactMatch = entries.find(e => e.specialisationLower === specLower);
  if (exactMatch) {
    const plan = JSON.parse(JSON.stringify(exactMatch.plan)) as StudyPlanResponse;
    plan.generatedAt = today();
    return plan;
  }

  // Try partial match
  const partialMatch = entries.find(e =>
    e.specialisationLower !== '' && specLower.includes(e.specialisationLower)
  );
  if (partialMatch) {
    const plan = JSON.parse(JSON.stringify(partialMatch.plan)) as StudyPlanResponse;
    plan.generatedAt = today();
    return plan;
  }

  // Return default (first entry)
  const defaultEntry = entries.find(e => e.specialisationLower === '') || entries[0];
  const plan = JSON.parse(JSON.stringify(defaultEntry.plan)) as StudyPlanResponse;
  plan.generatedAt = today();
  return plan;
}

export function hasFallbackPlan(programCode: string): boolean {
  return programCode in FALLBACK_REGISTRY;
}
