import { ProgramCatalogue } from './types';

const mockProgrammes: Record<string, ProgramCatalogue> = {
  '62510': {
    programCode: '62510',
    programName: 'Master of Information Technology',
    totalCreditPoints: 96,
    defaultUnitsPerSemester: 4,
    specialisations: [
      {
        code: 'SP-APCMP',
        name: 'Applied Computing',
        coreUnits: ['CITS4009', 'CITS4012', 'CITS4013', 'CITS5017', 'CITS5018'],
        electiveOptions: ['CITS4402', 'CITS4403', 'CITS4404', 'CITS5508', 'CITS5509', 'CITS5510', 'CITS5205', 'CITS5553', 'CITS5019', 'CITS5020', 'CITS5021'],
        description: 'Focus on practical computing skills across software, data, and systems.',
      },
      {
        code: 'SP-ARTIN',
        name: 'Artificial Intelligence',
        coreUnits: ['CITS4009', 'CITS4012', 'CITS4404', 'CITS5017', 'CITS5509'],
        electiveOptions: ['CITS4402', 'CITS4403', 'CITS5508', 'CITS5510', 'CITS5021'],
        description: 'Deep dive into AI, machine learning, and intelligent systems.',
      },
      {
        code: 'SP-SFTSY',
        name: 'Software Systems',
        coreUnits: ['CITS4012', 'CITS4013', 'CITS5017', 'CITS5205', 'CITS5553'],
        electiveOptions: ['CITS5501', 'CITS5503', 'CITS5020', 'CITS4403', 'CITS4419', 'CITS5506'],
        description: 'Advanced software engineering, cloud systems, and cybersecurity.',
      },
    ],
    sequenceData: [],
    prerequisiteChains: [],
    constraints: [
      {
        code: 'STRICT_PREREQUISITES',
        description: 'All prerequisite chains must be satisfied before enrolment in dependent units.',
        priority: 'mandatory',
      },
      {
        code: 'AVAILABILITY_ONLY',
        description: 'Units should only be placed in semesters where they are offered.',
        priority: 'preferred',
      },
      {
        code: 'CORE_COMPLETION',
        description: 'Core units are compulsory and should be prioritised early where possible.',
        priority: 'preferred',
      },
      {
        code: 'TOTAL_CREDIT_TARGET',
        description: 'The study plan should reach 96 credit points in total.',
        priority: 'informational',
      },
    ],
    units: [
      {
        code: 'CITS4009',
        title: 'Computational Data Analysis',
        creditPoints: 6,
        type: 'core',
        availability: ['S1'],
        prerequisites: [],
        incompatibilities: [],
        corequisites: [],
        description: 'Foundational data analysis and computational thinking for postgraduate IT students.',
      },
      {
        code: 'CITS4012',
        title: 'Software Engineering Principles',
        creditPoints: 6,
        type: 'core',
        availability: ['S1', 'S2'],
        prerequisites: [],
        incompatibilities: [],
        corequisites: [],
        description: 'Core engineering methods for software quality, planning and delivery.',
      },
      {
        code: 'CITS4013',
        title: 'Database Systems',
        creditPoints: 6,
        type: 'core',
        availability: ['S2'],
        prerequisites: [],
        incompatibilities: [],
        corequisites: [],
        description: 'Relational modelling, SQL and transactional data management.',
      },
      {
        code: 'CITS4402',
        title: 'Computer Vision',
        creditPoints: 6,
        type: 'elective',
        availability: ['S1'],
        prerequisites: ['CITS4009'],
        description: 'Image processing and visual learning techniques for intelligent systems.',
      },
      {
        code: 'CITS4403',
        title: 'Artificial Intelligence',
        creditPoints: 6,
        type: 'elective',
        availability: ['S2'],
        prerequisites: ['CITS4009'],
        description: 'Search, reasoning and intelligent agent methods with practical applications.',
      },
      {
        code: 'CITS4404',
        title: 'Machine Learning',
        creditPoints: 6,
        type: 'elective',
        availability: ['S1'],
        prerequisites: ['CITS4009'],
        description: 'Supervised and unsupervised methods, model evaluation and deployment concerns.',
      },
      {
        code: 'CITS5508',
        title: 'Data Mining',
        creditPoints: 6,
        type: 'elective',
        availability: ['S2'],
        prerequisites: ['CITS4013'],
        description: 'Pattern discovery and predictive methods for large-scale datasets.',
      },
      {
        code: 'CITS5509',
        title: 'Deep Learning',
        creditPoints: 6,
        type: 'elective',
        availability: ['S2'],
        prerequisites: ['CITS4404'],
        description: 'Neural network architectures and practical deep learning workflows.',
      },
      {
        code: 'CITS5510',
        title: 'Natural Language Processing',
        creditPoints: 6,
        type: 'elective',
        availability: ['S1'],
        prerequisites: ['CITS4404'],
        description: 'Text analytics, language models and practical NLP pipelines.',
      },
      {
        code: 'CITS5205',
        title: 'Cloud Computing',
        creditPoints: 6,
        type: 'elective',
        availability: ['S1', 'S2'],
        prerequisites: ['CITS4012'],
        description: 'Distributed systems, deployment architecture and scalable cloud services.',
      },
      {
        code: 'CITS5553',
        title: 'Cyber Security',
        creditPoints: 6,
        type: 'elective',
        availability: ['S2'],
        prerequisites: ['CITS4012'],
        description: 'Threat models, secure design and defensive techniques across modern systems.',
      },
      {
        code: 'CITS5017',
        title: 'Professional Computing Project',
        creditPoints: 6,
        type: 'core',
        availability: ['S1', 'S2'],
        prerequisites: ['CITS4012', 'CITS4013'],
        description: 'Capstone project integrating technical design and professional delivery practices.',
      },
      {
        code: 'CITS5018',
        title: 'IT Research Methods',
        creditPoints: 6,
        type: 'core',
        availability: ['S1'],
        prerequisites: [],
        incompatibilities: [],
        corequisites: [],
        description: 'Research design, evaluation methods and evidence-led technical investigation.',
      },
      {
        code: 'CITS5019',
        title: 'Enterprise Systems',
        creditPoints: 6,
        type: 'elective',
        availability: ['S2'],
        prerequisites: ['CITS4013'],
        description: 'Enterprise architecture, integration and large-scale information systems.',
      },
      {
        code: 'CITS5020',
        title: 'Advanced Software Architecture',
        creditPoints: 6,
        type: 'elective',
        availability: ['S1'],
        prerequisites: ['CITS4012'],
        description: 'Architectural patterns and decision-making for complex software platforms.',
      },
      {
        code: 'CITS5021',
        title: 'Responsible AI',
        creditPoints: 6,
        type: 'elective',
        availability: ['S2'],
        prerequisites: ['CITS4403'],
        description: 'Ethics, governance and safety practices for AI system development.',
      },
    ],
  },
};

export function getMockProgrammeCatalogue(programmeCode: string): ProgramCatalogue | null {
  return mockProgrammes[programmeCode] ?? null;
}
